name: Deploy to AWS

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Backup old build
        run: |
          ssh -t -i ~/.ssh/id_ed25519 ubuntu@${{ secrets.SERVER_IP }} "
            cd /var/www/hangman &&
            if [ -d build ]; then
              mv build build_old_$(date +%Y%m%d%H%M%S)
            fi
            mkdir -p build"

      - name: Ensure new build directory is empty
        run: |
          ssh -t -i ~/.ssh/id_ed25519 ubuntu@${{ secrets.SERVER_IP }} "
            cd /var/www/hangman &&
            if [ \"\$(ls -A build)\" ]; then
              echo 'ERROR: build directory is not empty!' && exit 1
            fi"

      - name: Deploy new build via SCP
        run: scp -r -i ~/.ssh/id_ed25519 build/* ubuntu@${{ secrets.SERVER_IP }}:/var/www/hangman/build/

      - name: Restart Nginx
        run: ssh -t -i ~/.ssh/id_ed25519 ubuntu@${{ secrets.SERVER_IP }} "sudo systemctl restart nginx"

      - name: Cleanup old builds
        run: |
          ssh -t -i ~/.ssh/id_ed25519 ubuntu@${{ secrets.SERVER_IP }} "
            cd /var/www/hangman &&
            ls -dt build_old_* | tail -n +6 | xargs rm -rf || true"
